import React,{useState,useEffect} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Search,ShoppingBag,Heart,User,ChevronDown,Menu,X,ArrowUpRight,ArrowRight,Grid2X2,Sun,Moon,Scale,Truck,Bell,Headset} from 'lucide-react';
import {useStore} from '../../lib/store';
import {get,post} from '../../lib/api';
import {Product} from '../../lib/types';

export const Logo=({admin=false}:any)=>{const {config}=useStore();const logo=config?.settings?.brand_logo;return <Link data-testid={admin?'admin-logo':'store-logo'} className="logo" to={admin?'/admin':'/'}>{logo?<img src={logo} alt={config?.settings.brand||'VOLTORA'} style={{height:(config?.settings?.brand_logo_height||36)+'px',width:'auto'}}/>:<><span className="logo-mark"><i/><i/><i/></span>{config?.settings.brand||'VOLTORA'}<span className="logo-dot">®</span></>}</Link>;};
import {adminHref} from '../../lib/adminPath';

export const Header=()=>{
 const {config,cart,wishlist,compare,language,setLanguage,currency,setCurrency,t,user,mode,setMode,money}=useStore();const s=config.settings,f=s.features;const hc=s.header_config||{};
 const [q,setQ]=useState(''),[suggestions,setSuggestions]=useState<Product[]>([]),[show,setShow]=useState(false),[menu,setMenu]=useState(false),[mega,setMega]=useState(false),[notes,setNotes]=useState<any>(null),[notesOpen,setNotesOpen]=useState(false);const nav=useNavigate();
 useEffect(()=>{if(!user){setNotes(null);return;}const load=()=>get('/notifications').then(setNotes).catch(()=>{});load();const timer=setInterval(load,30000);return()=>clearInterval(timer);},[user?.id]);
 useEffect(()=>{if(q.trim().length<2){setSuggestions([]);return;}const timer=setTimeout(()=>get(`/products?q=${encodeURIComponent(q)}&limit=5`).then(r=>setSuggestions(r.items)).catch(()=>setSuggestions([])),250);return()=>clearTimeout(timer);},[q]);
 const search=(e:any)=>{e.preventDefault();setShow(false);nav('/shop?q='+encodeURIComponent(q));};
 const count=cart.reduce((n:number,c:any)=>n+c.quantity,0);
 // website-builder site document: when published, header structure comes from blocks; otherwise the classic layout
 const hd=config.site?.header;const hasBlocks=!!(hd&&(hd.top?.length||hd.main?.length||hd.actions?.length));
 const on=(k:string)=>hc[k]!==false;
 const enabled=(zone:string,type:string)=>!hasBlocks||(hd[zone]||[]).some((b:any)=>b.type===type&&b.enabled!==false);
 const blockLabel=(type:string,fallback:string)=>{const b=(hd?.top||[]).find((x:any)=>x.type===type);return (b?.label||fallback);};
 const showAnnouncement=s.announcement&&enabled('top','announcement')&&(hc.show_announcement!==false);
 const announcementCta=hc.show_announcement_cta!==false&&enabled('top','announcement');
 const utilityMsg=hasBlocks?((hd.top||[]).find((b:any)=>b.type==='utility_message')?.label||hd.utility_message||''):'Thoughtfully selected. Exceptionally yours.';
 const headerClass='store-header'+(hd?(hd.sticky?' sticky-header':' header-'+(hd.layout||'classic')):(on('sticky')?' sticky-header':''));
 const SearchBlock=hasBlocks&&!enabled('main','search')?null:
  <form className="search-form" onSubmit={search}><Search size={19}/><input data-testid="header-search" aria-label="Search products" placeholder={t('search')} value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>setShow(true)} onBlur={()=>setTimeout(()=>setShow(false),180)}/><button data-testid="header-search-submit" aria-label="Search" type="submit"><ArrowRight size={18}/></button>{show&&suggestions.length>0&&<div className="search-results" data-testid="search-suggestions"><span className="eyebrow">PRODUCTS</span>{suggestions.map(p=><Link data-testid={`search-result-${p.id}`} to={'/product/'+p.slug} key={p.id} onClick={()=>{setShow(false);setQ('');}}><img src={p.images[0]} alt=""/><span>{p.name}<small>{p.brand}</small></span><b>{money(p.price)}</b></Link>)}<button type="submit" data-testid="search-all-results">View all results <ArrowRight size={14}/></button></div>}</form>;
 const notificationsBlock=user&&f.notifications!==false&&enabled('actions','notifications')&&<div className="notes-wrap"><button className="icon-btn" data-testid="notifications-bell" title="Notifications" onClick={()=>setNotesOpen(!notesOpen)}><Bell size={20}/>{!!notes?.unread&&<b className="small-count" data-testid="notifications-count">{notes.unread}</b>}</button>{notesOpen&&<div className="notes-panel" data-testid="notifications-panel"><div className="notes-head"><b>Notifications</b>{notes?.items?.length>0&&<button className="text-link" onClick={async()=>{await post('/notifications/read-all');get('/notifications').then(setNotes).catch(()=>{});}}>Mark all read</button>}</div>{notes?.items?.length?notes.items.map((n:any)=><button key={n.id} className={'note-item'+(n.read?'':' unread')} onClick={async()=>{if(!n.read)await post('/notifications/'+n.id+'/read');setNotesOpen(false);if(n.link)nav(n.link);}}><b>{n.title}</b><small>{n.body}</small><span>{new Date(n.created_at).toLocaleDateString()}</span></button>):<p className="small-note" style={{padding:14}}>Nothing here yet. Order and support updates appear here.</p>}</div>}</div>;
 const darkBlock=f.dark_mode&&(hasBlocks?enabled('actions','dark_mode'):true)&&<button className="icon-btn theme-toggle" data-testid="theme-mode-toggle" title={mode==='dark'?'Switch to light mode':'Switch to dark mode'} onClick={()=>setMode(mode==='dark'?'light':'dark')}>{mode==='dark'?<Sun size={20}/>:<Moon size={20}/>}</button>;
 const compareBlock=f.compare&&(hasBlocks?enabled('actions','compare'):false)&&<Link data-testid="compare-link" to="/compare" className="header-action"><Scale size={21}/><span>Compare</span>{compare.length>0&&<b className="small-count">{compare.length}</b>}</Link>;
 const actionMap:any={notifications:notificationsBlock,dark_mode:darkBlock,compare:compareBlock,
  account:<Link data-testid="account-link" to="/account" className="header-action"><User size={21}/><span>{user?user.name.split(' ')[0]:t('account')}</span></Link>,
  wishlist:f.wishlist&&(hasBlocks?enabled('actions','wishlist'):on('show_wishlist'))?<Link data-testid="wishlist-link" to="/wishlist" className="header-action"><Heart size={21}/><span>{t('wishlist')}</span>{wishlist.length>0&&<b className="small-count">{wishlist.length}</b>}</Link>:null,
  cart:<Link data-testid="cart-link" to="/cart" className="header-action cart-action"><span className="bag-icon"><ShoppingBag size={21}/><b data-testid="cart-count">{count}</b></span><span>{t('cart')}</span></Link>}; const actionsRender=hasBlocks?(hd.actions||[]).map((b:any,i:number)=><React.Fragment key={b.id||b.type+'-'+i}>{b.enabled!==false?actionMap[b.type]||null:null}</React.Fragment>):Object.keys(actionMap).filter((k:string)=>k==='notifications'||k==='dark_mode'||k==='account'||(k==='wishlist'&&f.wishlist&&on('show_wishlist'))||k==='cart').map(k=><React.Fragment key={k}>{actionMap[k]}</React.Fragment>);
 const showNav=hasBlocks?hd.show_nav!==false:true;
 const showBrowse=hasBlocks?hd.show_browse!==false:true;
 const navDeal=hasBlocks?(hd.nav_deal_label||'New arrivals'):'New arrivals';
 return <>
  {showAnnouncement&&<div className="announcement"><div className="container"><span data-testid="announcement-text">{s.demo_catalog?'DEMO STORE · ':''}{language==='bn'&&s.announcement_bn?s.announcement_bn:s.announcement}</span>{announcementCta&&<Link to="/shop" data-testid="announcement-shop">Shop now <ArrowUpRight size={13}/></Link>}</div></div>}
  {(hasBlocks?(hd.top||[]).some((b:any)=>b.enabled!==false&&['utility_message','track_order','support_link','language','currency'].includes(b.type)):(on('show_track_order')||true))&&<div className="utility container"><Link className="workspace-entry-link" data-testid="store-open-workspace" to={adminHref('')}>Workspace<ArrowUpRight size={13}/></Link><span data-testid="utility-message">{utilityMsg}</span><div>{hasBlocks?(hd.top||[]).filter((b:any)=>b.enabled!==false).map((b:any,i:number)=>{
    if(b.type==='track_order')return <Link data-testid="track-order-link" to="/account" key={i}><Truck size={13}/> {b.label||'Track your order'}</Link>;
    if(b.type==='support_link')return <Link data-testid="utility-support" to={b.url||'/support'} key={i}>{b.label||'Need a hand?'}</Link>;
    if(b.type==='language'&&f.multilingual)return <select aria-label="Language" data-testid="language-select" value={language} onChange={e=>setLanguage(e.target.value)} key={i}><option value="en">English</option><option value="bn">বাংলা</option></select>;
    if(b.type==='currency'&&f.multicurrency)return <select aria-label="Display currency" data-testid="currency-select" value={currency} onChange={e=>setCurrency(e.target.value)} key={i}>{s.currencies.filter((x:any)=>x.enabled).map((c:any)=><option key={c.code} value={c.code}>{c.code} {c.symbol}</option>)}</select>;
    return null;}).filter(Boolean):(hasBlocks?null:<>{on('show_track_order')&&<Link data-testid="track-order-link" to="/account"><Truck size={13}/> Track your order</Link>}<Link data-testid="utility-support" to="/support">Need a hand?</Link>{f.multilingual&&on('show_language')&&<select aria-label="Language" data-testid="language-select" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="bn">বাংলা</option></select>}{f.multicurrency&&on('show_currency')&&<select aria-label="Display currency" data-testid="currency-select" value={currency} onChange={e=>setCurrency(e.target.value)}>{s.currencies.filter((x:any)=>x.enabled).map((c:any)=><option key={c.code} value={c.code}>{c.code} {c.symbol}</option>)}</select>}</>)}</div></div>}
  <header className={headerClass}>
   <div className={'header-main container'+(hd?.layout==='centered'?' header-centered':'')}>{(hasBlocks?enabled('main','menu'):true)&&<button className="mobile-menu icon-btn" data-testid="mobile-menu-open" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></button>}{(hasBlocks?enabled('main','logo'):true)&&<Logo/>}{f.search&&(hasBlocks?enabled('main','search'):on('show_search'))&&SearchBlock}
    <div className="header-actions">{actionsRender}</div>
   </div>
   {showNav&&<nav className="main-nav container" aria-label="Main navigation">{showBrowse&&<div className="browse-wrap" onMouseEnter={()=>setMega(true)} onMouseLeave={()=>setMega(false)}><button data-testid="browse-categories" onClick={()=>setMega(!mega)} aria-expanded={mega}><Grid2X2 size={17}/><span>Browse categories</span><ChevronDown size={14}/></button>{mega&&<div className="mega-menu" data-testid="category-mega-menu">{config.categories.map((c:any)=><Link data-testid={`mega-category-${c.id}`} key={c.id} to={'/shop?category='+c.id} onClick={()=>setMega(false)}>{c.name}<ArrowUpRight size={15}/></Link>)}</div>}</div>}<div className="nav-links">{s.navigation.map((n:any,i:number)=><Link data-testid={`nav-link-${i}`} to={n.url} key={i}>{n.label}</Link>)}</div><Link className="nav-deal" data-testid="new-arrivals-link" to="/shop?sort=newest"><span/>{navDeal}<ArrowUpRight size={14}/></Link></nav>}
  </header>
  {menu&&<div className="mobile-menu-overlay" onClick={()=>setMenu(false)}><div className="mobile-menu-panel" role="dialog" aria-modal="true" aria-label="Store navigation" onClick={e=>e.stopPropagation()}><div><b>Explore {s.brand||'VOLTORA'}</b><button className="icon-btn" data-testid="mobile-menu-close" aria-label="Close menu" onClick={()=>setMenu(false)}><X/></button></div>{s.navigation.map((n:any,i:number)=><Link key={i} data-testid={`mobile-nav-${i}`} to={n.url} onClick={()=>setMenu(false)}>{n.label}<ArrowUpRight size={16}/></Link>)}<Link to="/support" data-testid="mobile-support" onClick={()=>setMenu(false)}>Customer support</Link><Link to="/admin" data-testid="mobile-admin" onClick={()=>setMenu(false)}>Store workspace</Link>{f.multilingual&&<select data-testid="mobile-language" aria-label="Language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="bn">বাংলা</option></select>}</div></div>}
  <nav className="mobile-bottom" aria-label="Mobile navigation"><Link data-testid="bottom-shop" to="/shop"><Grid2X2 size={20}/><span>Explore</span></Link>{f.wishlist&&<Link data-testid="bottom-wishlist" to="/wishlist"><Heart size={20}/><span>{t('wishlist')}</span></Link>}{f.compare&&<Link data-testid="bottom-compare" to="/compare"><Scale size={20}/><span>Compare</span></Link>}<Link data-testid="bottom-cart" to="/cart"><ShoppingBag size={20}/><span>{t('cart')} ({count})</span></Link><Link data-testid="bottom-account" to="/account"><User size={20}/><span>{t('account')}</span></Link></nav>
 </>;
};
