import React from 'react';
import {Link} from 'react-router-dom';
import {Heart,Plus,Check,Scale,Star,ArrowUpRight} from 'lucide-react';
import {Product} from '../../lib/types';
import {useStore} from '../../lib/store';

export const ProductCard=({product:p,prefix='product'}:{product:Product;prefix?:string})=>{
 const {money,add,wishlist,toggleWishlist,compare,toggleCompare,config,language,t}=useStore();const f=config.settings.features;
 const sale=p.compare_price>p.price;const saleEnds=p.sale_ends_at?new Date(p.sale_ends_at).getTime():0;const saleLive=saleEnds>Date.now();
 return <article className="product-card" data-testid={`${prefix}-card-${p.id}`}><div className="product-image"><Link to={'/product/'+p.slug} data-testid={`${prefix}-image-${p.id}`}><img loading="lazy" src={p.images[0]} alt={p.name}/></Link>{(p.badge||sale)&&<span className={'product-badge '+(sale?'sale':'')} data-testid={`${prefix}-badge-${p.id}`}>{sale?`−${Math.round((1-p.price/p.compare_price)*100)}%`:p.badge}</span>}{saleLive&&<span className="product-badge sale-live" data-testid={`${prefix}-sale-ends-${p.id}`} title={new Date(saleEnds).toLocaleString()}>Ends {new Date(saleEnds).toLocaleDateString()}</span>}{f.wishlist&&<button className={'product-heart '+(wishlist.includes(p.id)?'active':'')} data-testid={`${prefix}-wishlist-${p.id}`} aria-label={'Save '+p.name} aria-pressed={wishlist.includes(p.id)} onClick={()=>toggleWishlist(p.id)}><Heart size={17} fill={wishlist.includes(p.id)?'currentColor':'none'}/></button>}{f.compare&&<button className={'product-compare '+(compare.includes(p.id)?'active':'')} data-testid={`${prefix}-compare-${p.id}`} title="Compare product" onClick={()=>toggleCompare(p.id)}><Scale size={16}/></button>}</div><div className="product-meta"><span data-testid={`${prefix}-brand-${p.id}`}>{p.brand}</span>{p.review_count>0&&<span><Star size={11} fill="currentColor"/>{p.rating} <em>({p.review_count})</em></span>}</div><Link className="product-name" data-testid={`${prefix}-name-${p.id}`} to={'/product/'+p.slug}>{language==='bn'&&p.name_bn?p.name_bn:p.name}</Link><p className="product-subtitle" data-testid={`${prefix}-subtitle-${p.id}`}>{p.subtitle}</p><div className="product-bottom"><div><strong data-testid={`${prefix}-price-${p.id}`}>{money(p.price)}</strong>{sale&&<del data-testid={`${prefix}-original-price-${p.id}`}>{money(p.compare_price)}</del>}</div>{f.quick_add&&<button className="quick-add" data-testid={`${prefix}-add-${p.id}`} title={t('add')} disabled={p.stock===0} onClick={()=>add(p)}><Plus size={20}/></button>}</div>{p.stock===0&&<span className="out-stock">Out of stock</span>}</article>;
};