import React,{useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import * as Icons from 'lucide-react';
import {ArrowRight,ArrowUpRight,ChevronDown,Headphones,Truck,ShieldCheck,Headset,Plus} from 'lucide-react';
import {useStore} from '../../lib/store';
import {get} from '../../lib/api';
import {ProductCard} from './ProductCard';
import {Product,Section} from '../../lib/types';

const ProductsSection=({section:s}:any)=>{
 const [products,setProducts]=useState<Product[]>([]);const {language}=useStore();
 useEffect(()=>{if(s.product_ids&&s.product_ids.length){get(`/products?ids=${s.product_ids.join(',')}&limit=12`).then(r=>setProducts(r.items)).catch(()=>setProducts([]));}else{get(`/products?limit=${s.limit||4}${s.category?'&category='+s.category:''}${s.id==='new'?'&sort=newest':''}`).then(r=>setProducts(r.items)).catch(()=>setProducts([]));}},[s.limit,s.category,s.id,(s.product_ids||[]).join(',')]);
 return <section className="product-section container section-space"><div className="section-heading"><div>{s.eyebrow&&<span className="eyebrow">{s.eyebrow}</span>}<h2 data-testid={`section-title-${s.id}`}>{language==='bn'&&s.title_bn?s.title_bn:s.title}</h2>{s.subtitle&&<p>{language==='bn'&&s.subtitle_bn?s.subtitle_bn:s.subtitle}</p>}</div><Link className="text-link" data-testid={`section-link-${s.id}`} to={s.link||'/shop'}>{s.button||'View collection'}<ArrowUpRight size={17}/></Link></div><div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p} prefix={s.id}/>)}</div></section>;
};
export const SectionRenderer=({sections}:{sections:Section[]})=>{const {config,language}=useStore();return <>{sections.filter(s=>s.enabled!==false).map(s=>{
 const title=language==='bn'&&s.title_bn?s.title_bn:s.title;const subtitle=language==='bn'&&s.subtitle_bn?s.subtitle_bn:s.subtitle;
 let content:React.ReactNode=null;
 if(s.type==='hero'&&['compact','centered','panoramic'].includes(config.theme.hero_style))content=<section className={'container structural-hero structural-'+config.theme.hero_style}><div className="structural-hero-copy"><span className="eyebrow">{s.eyebrow}</span><h1 data-testid="hero-title">{title}</h1><p data-testid="hero-subtitle">{subtitle}</p><Link data-testid="hero-cta" className="v-button primary" to={s.link||'/shop'}>{s.button}<ArrowUpRight size={17}/></Link><span className="structural-index">VOLTORA / THOUGHTFULLY SELECTED</span></div><figure><img src={s.image} alt={title}/><figcaption>THE EVERYDAY COLLECTION</figcaption></figure></section>;
 else if(s.type==='hero')content=<section className="campaign-hero container"><div className="hero-inner" style={{backgroundImage:`url(${s.image})`}}><div className="hero-copy"><span className="hero-eyebrow"><span/> {s.eyebrow}</span><h1 data-testid="hero-title">{title}</h1><p data-testid="hero-subtitle">{subtitle}</p><Link data-testid="hero-cta" className="v-button primary" to={s.link}>{s.button}<ArrowUpRight size={17}/></Link><div className="hero-product-note"><span className="tiny-line"/><span>Considered design. Exceptional sound.</span></div></div><div className="hero-caption"><span>AURALIS / STUDIO SERIES</span><span>01 — 03</span></div></div></section>;
 else if(s.type==='features')content=<div className="trust-band container">{s.items.map((item,i)=>{const Icon=(Icons as any)[item.icon]||ShieldCheck;return <div key={i}><Icon size={25} strokeWidth={1.4}/><div><strong data-testid={`${s.id}-feature-${i}`}>{item.title}</strong><span>{item.text}</span></div></div>;})}</div>;
 else if(s.type==='categories')content=<section className="container category-section section-space"><div className="section-heading"><div><span className="eyebrow">{s.eyebrow}</span><h2 data-testid={`section-title-${s.id}`}>{title}</h2></div><Link className="text-link" to="/shop" data-testid="all-categories-link">Explore all<ArrowUpRight size={17}/></Link></div><div className="category-grid">{config.categories.map((c:any)=>{const Icon=(Icons as any)[c.icon]||Headphones;return <Link data-testid={`category-${c.id}`} className="category-item" key={c.id} to={'/shop?category='+c.id}><div className="category-icon"><Icon size={31} strokeWidth={1.25}/></div><span>{c.name}</span></Link>;})}</div></section>;
 else if(s.type==='products')content=<ProductsSection section={s}/>;
 else if(s.type==='image_text'||s.type==='banner')content=<section className="container editorial-section section-space"><div className="editorial" style={{backgroundImage:`url(${s.image})`}}><div><span className="eyebrow">{s.eyebrow}</span><h2 data-testid={`section-title-${s.id}`}>{title}</h2><p>{subtitle}</p><Link className="v-button" data-testid={`section-link-${s.id}`} to={s.link}>{s.button}<ArrowUpRight size={17}/></Link></div></div></section>;
 else if(s.type==='brands')content=<section className="container brand-section section-space"><p data-testid={`section-title-${s.id}`}>{title}</p><div>{config.brands.slice(0,6).map((b:any,i:number)=><Link key={b.id} data-testid={`brand-${b.id}`} className={'brand-wordmark brand-'+i} to={'/shop?brand='+b.name}>{b.name}{i===1&&<span>®</span>}</Link>)}</div></section>;
 else if(s.type==='cta')content=<section className="contact-band"><div className="container"><div><span className="eyebrow">{s.eyebrow}</span><h2 data-testid={`section-title-${s.id}`}>{title}</h2><p>{subtitle}</p></div><Link className="v-button primary" data-testid={`section-link-${s.id}`} to={s.link}>{s.button}<ArrowUpRight size={18}/></Link></div></section>;
 else if(s.type==='text')content=<section className="container content-text section-space"><span className="eyebrow">{s.eyebrow}</span><h1 data-testid={`section-title-${s.id}`}>{title}</h1><p data-testid={`section-text-${s.id}`}>{subtitle}</p></section>;
 else if(s.type==='image')content=<figure className="container section-space"><img className="content-image" src={s.image} alt={title}/><figcaption>{subtitle}</figcaption></figure>;
 else if(s.type==='faq')content=<section className="container content-text section-space"><h2>{title}</h2>{s.items.map((item,i)=><details data-testid={`${s.id}-faq-${i}`} key={i}><summary>{item.title}<Plus size={18}/></summary><p>{item.text}</p></details>)}</section>;
 else if(s.type==='divider')content=<div className="container"><hr/></div>;
 else if(s.type==='spacer')content=<div style={{height:s.padding||40}}/>;
 return <div key={s.id} data-testid={`section-${s.id}`} className={`${s.mobile===false?'hide-mobile':''} ${s.desktop===false?'hide-desktop':''}`} style={{textAlign:s.alignment as any,padding:s.padding||undefined,background:s.background||undefined,color:s.color||undefined,border:s.border?'1px solid var(--v-border)':undefined,fontSize:s.font_size||undefined}}>{content}</div>;
 })}</>;};