import React,{useState} from 'react';
import {Link,NavLink,Outlet,useLocation} from 'react-router-dom';
import {LayoutDashboard,Package,ShoppingBag,Users,Palette,PanelsTopLeft,Image,Settings,ShieldCheck,MessageSquare,Plug,BarChart3,LogOut,Menu,X,ArrowUpRight,Search,ChevronDown,Mail,Sparkles,Truck,Globe,Sun,Moon,Percent,Receipt,History,Layers3,Activity,Tag} from 'lucide-react';
import {useStore} from '../../lib/store';
import {Logo} from '../store/Header';
import {MfaPanel} from '../../pages/Account';
import {Loading,Modal,Field} from '../shared';
import {OwnerEntry} from './OwnerEntry';
import {toast} from 'sonner';
import {message} from '../../lib/api';
const groups:any[]=[
 ['WORKSPACE',[['','Overview',LayoutDashboard,'analytics.read'],['orders','Orders',ShoppingBag,'orders.read'],['products','Products',Package,'products.read'],['customers','Customers',Users,'customers.read'],['inventory','Inventory',Layers3,'inventory.read'],['analytics','Analytics',BarChart3,'analytics.read']]],
 ['STOREFRONT',[['website','Website builder',PanelsTopLeft,'content.read'],['themes','Theme library',Palette,'theme.read'],['releases','Release history',History,'content.read'],['media','Media library',Image,'media.read'],['collections','Collections',Tag,'catalog.read'],['categories','Categories',Layers3,'catalog.read'],['brands','Brands',Tag,'catalog.read'],['offers','Offer pages',Percent,'catalog.read']]],
 ['CONNECT',[['ai','Mira workspace',Sparkles,'ai.read'],['support','Customer support',MessageSquare,'support.read'],['mail','Mailbox',Mail,'mail.read'],['connections','Integrations',Plug,'settings.read'],['email-templates','Email templates',Mail,'settings.read'],['affiliates','Affiliates',Users,'marketing.read']]],
 ['MANAGE',[['settings','Store settings',Settings,'settings.read'],['team','Team',Users,'roles.read'],['security','Security',ShieldCheck,'security.read'],['roles','Roles & permissions',ShieldCheck,'roles.read'],['payments','Payments',Receipt,'payments.read'],['shipping','Shipping',Truck,'settings.read'],['couriers','Couriers',Truck,'couriers.read'],['locations','Locations',Globe,'locations.read'],['localization','Market & language',Globe,'settings.read'],['coupons','Discounts',Tag,'coupons.read'],['reviews','Reviews',MessageSquare,'products.read'],['audit','Activity log',History,'audit.read'],['diagnostics','Store health',Activity,'settings.read']]]
];
export const AdminShell=()=>{
 const {user,authReady,logout}=useStore();const location=useLocation();const [mobile,setMobile]=useState(false),[search,setSearch]=useState(false),[q,setQ]=useState(''),[expanded,setExpanded]=useState<string[]>([]),[dark,setDark]=useState(localStorage.getItem('voltora-admin-dark')==='true');
 if(!authReady)return <Loading/>;
 if(!user)return <OwnerEntry/>;
 if(user.role==='customer')return <div className="mfa-page"><ShieldCheck size={35}/><h1>Owner and staff access only.</h1><Link data-testid="return-customer-account" to="/account">Back to your account</Link></div>;
 if(!user.mfa_verified)return <MfaPanel/>;
 if(location.pathname==='/admin/website')return <Outlet/>;
 const all=groups.flatMap(g=>g[1]).filter((n:any)=>user.permissions.includes(n[3]));const current=all.find((n:any)=>location.pathname==='/admin'+(n[0]?'/'+n[0]:''));
 return <div className={'admin-shell v2-workspace workspace-sidebar '+(dark?'admin-dark':'')}>
 {mobile&&<button className="admin-sidebar-overlay" data-testid="close-nav-overlay" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <aside className={'admin-sidebar '+(mobile?'open':'')}><div className="admin-brand"><Logo admin/><span>WORKSPACE</span><button className="icon-btn mobile-only" aria-label="Close menu" data-testid="admin-close-menu" onClick={()=>setMobile(false)}><X size={18}/></button></div><div className="workspace-select"><span className="workspace-store-mark">V</span><span><b>VOLTORA Store</b><small>Private owner workspace</small></span><ShieldCheck size={15}/></div><nav className="admin-nav" aria-label="Workspace navigation">{groups.map(([label,links]:any)=>{const items=links.filter((n:any)=>user.permissions.includes(n[3])),open=expanded.includes(label),initial=label==='WORKSPACE'?4:3;return items.length>0&&<div className="nav-group" key={label}><span className="nav-group-label">{label}</span>{items.slice(0,open?50:initial).map(([id,text,Icon]:any)=><NavLink end data-testid={'admin-nav-'+(id||'overview')} className={({isActive})=>isActive?'active':''} key={id} to={'/admin'+(id?'/'+id:'')} onClick={()=>setMobile(false)}><Icon size={17}/><span>{text}</span></NavLink>)}{items.length>initial&&<button data-testid={'nav-more-'+label.toLowerCase()} className="nav-more" onClick={()=>setExpanded(open?expanded.filter(x=>x!==label):[...expanded,label])}>{open?'Show less':'More tools'}<ChevronDown size={13}/></button>}</div>;})}</nav><div className="sidebar-bottom"><Link to="/" data-testid="admin-view-store"><Globe size={17}/>Visit storefront<ArrowUpRight size={15}/></Link><Link to="/account" data-testid="admin-user-profile"><span className="avatar-initials">{user.name[0]}</span><span><b>{user.name}</b><small>{user.role.replaceAll('_',' ')} · MFA verified</small></span><Settings size={15}/></Link></div></aside>
 <div className="admin-main"><header className="admin-topbar"><div className="topbar-location"><button className="icon-btn mobile-only" data-testid="admin-mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={22}/></button><span>Workspace</span><span className="breadcrumb-divider">/</span><b data-testid="admin-page-name">{current?.[1]||'Store settings'}</b><span className="environment-pill"><i/>Sandbox</span></div><div className="topbar-actions"><button className="command-trigger" data-testid="admin-global-search" onClick={()=>setSearch(true)}><Search size={16}/><span>Find a workspace…</span></button><button className="icon-btn" data-testid="admin-dark-toggle" aria-label="Toggle workspace appearance" onClick={()=>{setDark(!dark);localStorage.setItem('voltora-admin-dark',String(!dark));}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-btn" data-testid="admin-logout" aria-label="Sign out" onClick={()=>logout().catch((e:any)=>toast.error(message(e)))}><LogOut size={18}/></button></div></header><main className="admin-content" id="workspace-main"><Outlet/></main><footer className="workspace-footer"><span><i/>Isolated environment · External actions locked</span><span>Made for what’s next. <b>VOLTORA</b></span></footer></div>
 <Modal open={search} onClose={()=>setSearch(false)} title="Where would you like to go?"><Field id="command-search-input" label="Find a page" value={q} autoFocus onChange={(e:any)=>setQ(e.target.value)}/><div className="command-results">{all.filter((n:any)=>n[1].toLowerCase().includes(q.toLowerCase())).map(([id,label,Icon]:any)=><Link data-testid={'command-link-'+(id||'overview')} key={id} to={'/admin'+(id?'/'+id:'')} onClick={()=>setSearch(false)}><Icon size={17}/><span>{label}</span><ArrowUpRight size={15}/></Link>)}</div></Modal>
 </div>;
};