import React,{useState} from 'react';
import {File,Home,LogIn,UserPlus,KeyRound,ShoppingBag,ShoppingCart,CreditCard,User,PanelTop,PanelBottom,ChevronDown,ChevronRight,Plus,Search,Layers,GripVertical} from 'lucide-react';
const routes:any[]=[['page:home','Home',Home],['shop','Shop',ShoppingBag],['product','Product',ShoppingBag],['login','Login',LogIn],['signup','Sign up',UserPlus],['forgot-password','Password recovery',KeyRound],['account','Account',User],['cart','Cart',ShoppingCart],['checkout','Checkout',CreditCard]];
export const BuilderTree=({bundle,selection,select,onNewPage,selectedSection,setSelectedSection,edit}:any)=>{
 const [q,setQ]=useState(''),[pages,setPages]=useState(true),[components,setComponents]=useState(true);const [drag,setDrag]=useState<number|null>(null);
 const all=[...routes,...Object.values(bundle.pages).filter((p:any)=>p.slug!=='home').map((p:any)=>['page:'+p.slug,p.title,File])];
 const sections=selection.startsWith('page:')?bundle.pages[selection.slice(5)]?.sections:[];
 const reorder=(to:number)=>{if(drag===null||drag===to)return;const next=JSON.parse(JSON.stringify(bundle)),s=next.pages[selection.slice(5)].sections;const item=s.splice(drag,1)[0];s.splice(to,0,item);edit(next);setDrag(null);};
 return <aside className="ed-tree"><div className="ed-panel-title"><span>Pages & layers</span><button title="Add custom page" aria-label="Add custom page" data-testid="builder-add-page" onClick={onNewPage}><Plus size={16}/></button></div><label className="ed-search"><Search size={14}/><input data-testid="builder-search-pages" aria-label="Search pages" placeholder="Find a page…" value={q} onChange={e=>setQ(e.target.value)}/><span>/</span></label><button className="ed-tree-group" data-testid="toggle-storefront-pages" onClick={()=>setPages(!pages)}>{pages?<ChevronDown size={12}/>:<ChevronRight size={12}/>} STOREFRONT <span>{all.length}</span></button>{pages&&<div className="ed-page-list">{all.filter((r:any)=>r[1].toLowerCase().includes(q.toLowerCase())).map(([id,label,Icon]:any)=><React.Fragment key={id}><button className={'ed-tree-item '+(selection===id?'selected':'')} data-testid={'builder-page-'+id.replace(':','-')} onClick={()=>{select(id);setSelectedSection(null);}}><Icon size={15}/><span>{label}</span>{id==='page:home'&&<small>/</small>}{selection===id&&<i/>}</button>{selection===id&&sections?.length>0&&<div className="ed-layers">{sections.map((s:any,i:number)=><button draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>reorder(i)} data-testid={'builder-layer-'+s.id} key={s.id} className={selectedSection===s.id?'active':''} onClick={()=>setSelectedSection(s.id)}><GripVertical size={11}/><Layers size={12}/><span>{s.title?.split('\n')[0]||s.type}</span></button>)}</div>}</React.Fragment>)}</div>}<div className="ed-tree-divider"/><button className="ed-tree-group" data-testid="toggle-global-components" onClick={()=>setComponents(!components)}>{components?<ChevronDown size={12}/>:<ChevronRight size={12}/>} GLOBAL COMPONENTS <span>2</span></button>{components&&[['header','Header',PanelTop],['footer','Footer',PanelBottom]].map(([id,label,Icon]:any)=><button key={id} data-testid={'builder-component-'+id} className={'ed-tree-item '+(selection===id?'selected':'')} onClick={()=>{select(id);setSelectedSection(null);}}><Icon size={15}/><span>{label}</span><span className="ed-global-indicator"><Layers size={11}/></span></button>)}<div className="ed-tree-bottom"><span className="ed-tiny-label">CURRENT THEME</span><button data-testid="builder-theme-settings" className={'ed-theme-tile '+(selection==='theme'?'active':'')} onClick={()=>select('theme')}><div className="ed-theme-colors"><i style={{background:bundle.theme.primary}}/><i style={{background:bundle.theme.text}}/><i style={{background:bundle.theme.background}}/></div><span><strong>{bundle.theme.name}</strong><small>{bundle.theme.industry}</small></span><ChevronRight size={14}/></button></div></aside>;
};