import React,{useState} from 'react';
import {ChevronDown,Layers,ArrowUpRight,Type,Palette,MoveUp,MoveDown,Plus,Trash2,Check} from 'lucide-react';

const Input=({id,label,value,onChange,multiline=false,...props}:any)=>{const Tag=multiline?'textarea':'input';return <label className="ed-field"><span>{label}</span><Tag data-testid={id} value={value??''} onChange={(e:any)=>onChange(e.target.value)} {...props}/></label>;};
const Select=({id,label,value,onChange,options}:any)=><label className="ed-field"><span>{label}</span><select data-testid={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map((o:any)=><option key={typeof o==='string'?o:o[0]} value={typeof o==='string'?o:o[0]}>{typeof o==='string'?o:o[1]}</option>)}</select></label>;
const Toggle=({id,label,value,onChange}:any)=><label className="ed-toggle"><span>{label}</span><button data-testid={id} role="switch" aria-label={label} aria-checked={!!value} className={value?'on':''} onClick={()=>onChange(!value)}><i/></button></label>;
export const BuilderInspector=({bundle,edit,selection,customerState,setCustomerState,selectedSection}:any)=>{
 const [tab,setTab]=useState('content');const auth=['login','signup','forgot-password'].includes(selection),footer=selection==='footer';
 const patch=(part:string,value:any)=>edit({...bundle,site:{...bundle.site,[part]:{...bundle.site[part],...value}}});
 const theme=(value:any)=>edit({...bundle,theme:{...bundle.theme,...value}});
 const page=selection.startsWith('page:')?bundle.pages[selection.slice(5)]:null;
 const section=page?.sections.find((s:any)=>s.id===selectedSection);
 const patchSection=(p:any)=>edit({...bundle,pages:{...bundle.pages,[page.slug]:{...page,sections:page.sections.map((s:any)=>s.id===selectedSection?{...s,...p}:s)}}});
 const titles:any={login:'Login',signup:'Sign up','forgot-password':'Password recovery',footer:'Footer',header:'Header',theme:'Theme',checkout:'Checkout'};
 const columns=bundle.site.footer.columns;
 const updateCol=(i:number,p:any)=>patch('footer',{columns:columns.map((c:any,j:number)=>j===i?{...c,...p}:c)});
 const moveCol=(i:number,dir:number)=>{const c=[...columns];[c[i],c[i+dir]]=[c[i+dir],c[i]];patch('footer',{columns:c});};
 return <aside className="ed-inspector"><div className="ed-panel-title"><span>Properties</span><span className="ed-component-type">{footer||selection==='header'?'GLOBAL':'PAGE'}</span></div><div className="ed-inspector-heading"><div className="ed-node-icon">{footer?<Layers size={19}/>:selection==='theme'?<Palette size={19}/>:<Type size={19}/>}</div><div><h2 data-testid="inspector-title">{section?section.type:titles[selection]||page?.title||selection}</h2><span>{footer?'Shared component':auth?'Customer account':'Storefront'}</span></div></div><div className="ed-inspector-tabs">{['content','design'].map(t=><button data-testid={'inspector-tab-'+t} className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='content'?'Content':'Design'}</button>)}</div><div className="ed-inspector-scroll">
 {footer&&<div className="ed-impact" data-testid="footer-global-impact"><div><Layers size={14}/><strong>Shared across your storefront</strong></div><p>Home, Shop, Product, Login, Sign up, Account, Cart, Checkout and {Object.keys(bundle.pages).length-1} custom pages.</p><span>Changes take effect together on publish.<ArrowUpRight size={12}/></span></div>}
 {auth&&<><div className="ed-section-label">CUSTOMER STATE <ChevronDown size={12}/></div><div className="ed-state-grid">{[['login','Sign in'],['signup','Create account'],['forgot','Recovery'],['error','Error'],['success','Success']].map(([id,label])=><button key={id} data-testid={'preview-state-'+id} className={customerState===id?'active':''} onClick={()=>setCustomerState(id)}>{customerState===id&&<Check size={11}/>} {label}</button>)}</div></>}
 {tab==='content'&&auth&&<><div className="ed-section-label">WELCOME PANEL <ChevronDown size={12}/></div><Input id="auth-side-heading" label="Heading" multiline maxLength={160} value={bundle.site.auth.side_heading} onChange={(v:string)=>patch('auth',{side_heading:v})}/><Input id="auth-side-text" label="Description" multiline maxLength={400} value={bundle.site.auth.side_text} onChange={(v:string)=>patch('auth',{side_text:v})}/><Input id="auth-side-image" label="Image URL" value={bundle.site.auth.side_image} placeholder="Default brand image" onChange={(v:string)=>patch('auth',{side_image:v})}/><div className="ed-section-label">SIGN-IN FORM <ChevronDown size={12}/></div><Input id="auth-form-title" label="Form heading" maxLength={80} value={bundle.site.auth.form_title||'Welcome back.'} onChange={(v:string)=>patch('auth',{form_title:v})}/><Input id="auth-button-label" label="Button label" maxLength={40} value={bundle.site.auth.button_label||'Sign in'} onChange={(v:string)=>patch('auth',{button_label:v})}/><Input id="auth-card-note" label="Privacy note" value={bundle.site.auth.card_note} maxLength={200} onChange={(v:string)=>patch('auth',{card_note:v})}/></>}
 {tab==='content'&&footer&&<><div className="ed-section-label">FOOTER CONTENT <ChevronDown size={12}/></div><Input id="footer-copyright" label="Copyright line" value={bundle.site.footer.copyright} maxLength={200} onChange={(v:string)=>patch('footer',{copyright:v})}/>{columns.map((c:any,i:number)=><div className="ed-column-editor" key={c.id}><div className="ed-column-heading"><span>{c.type}</span><button data-testid={'footer-up-'+c.id} title="Move column left" disabled={i===0} onClick={()=>moveCol(i,-1)}><MoveUp size={13}/></button><button data-testid={'footer-down-'+c.id} title="Move column right" disabled={i===columns.length-1} onClick={()=>moveCol(i,1)}><MoveDown size={13}/></button><button data-testid={'footer-remove-'+c.id} title="Remove column" onClick={()=>patch('footer',{columns:columns.filter((_:any,j:number)=>j!==i)})}><Trash2 size={13}/></button></div><Toggle id={'footer-visible-'+c.id} label="Visible" value={c.enabled} onChange={(v:boolean)=>updateCol(i,{enabled:v})}/>{c.type!=='brand'&&<Input id={'footer-heading-'+c.id} label="Heading" maxLength={120} value={c.title} onChange={(v:string)=>updateCol(i,{title:v})}/>}<Input id={'footer-text-'+c.id} label="Text" multiline value={c.text} maxLength={500} onChange={(v:string)=>updateCol(i,{text:v})}/>{c.type==='links'&&c.links.map((l:any,j:number)=><div className="ed-link-fields" key={j}><Input id={`footer-${c.id}-link-${j}-label`} label="Link label" value={l.label} onChange={(v:string)=>updateCol(i,{links:c.links.map((x:any,n:number)=>n===j?{...x,label:v}:x)})}/><Input id={`footer-${c.id}-link-${j}-url`} label="Destination" value={l.url} onChange={(v:string)=>updateCol(i,{links:c.links.map((x:any,n:number)=>n===j?{...x,url:v}:x)})}/></div>)}</div>)}{columns.length<6&&<button className="ed-outline wide" data-testid="footer-add-column" onClick={()=>patch('footer',{columns:[...columns,{id:'text-'+Date.now(),type:'text',enabled:true,title:'A little about us',text:'',links:[]}]})}><Plus size={14}/>Add text column</button>}</>}
 {tab==='content'&&selection==='header'&&<><div className="ed-section-label">NAVIGATION</div><Toggle id="header-sticky" label="Sticky header" value={bundle.site.header.sticky} onChange={(v:boolean)=>patch('header',{sticky:v})}/><Toggle id="header-nav-visible" label="Show navigation" value={bundle.site.header.show_nav} onChange={(v:boolean)=>patch('header',{show_nav:v})}/><Input id="header-highlight-label" label="Highlighted link" value={bundle.site.header.nav_deal_label} onChange={(v:string)=>patch('header',{nav_deal_label:v})}/></>}
 {tab==='content'&&page&&<><div className="ed-section-label">{section?'SECTION CONTENT':'PAGE DETAILS'}</div>{section?<><Input id="section-heading" label="Heading" value={section.title} multiline onChange={(v:string)=>patchSection({title:v})}/><Input id="section-description" label="Description" value={section.subtitle} multiline onChange={(v:string)=>patchSection({subtitle:v})}/><Input id="section-image" label="Image URL" value={section.image} onChange={(v:string)=>patchSection({image:v})}/><Input id="section-button" label="Button label" value={section.button} onChange={(v:string)=>patchSection({button:v})}/><Input id="section-link" label="Button destination" value={section.link} onChange={(v:string)=>patchSection({link:v})}/><Toggle id="section-visible" label="Visible" value={section.enabled} onChange={(v:boolean)=>patchSection({enabled:v})}/></>:<><Input id="page-title" label="Page title" value={page.title} onChange={(v:string)=>edit({...bundle,pages:{...bundle.pages,[page.slug]:{...page,title:v}}})}/><Input id="page-seo-description" label="SEO description" value={page.seo_description} multiline onChange={(v:string)=>edit({...bundle,pages:{...bundle.pages,[page.slug]:{...page,seo_description:v}}})}/></>}</>}
 {(tab==='design'||selection==='theme')&&<><div className="ed-section-label">LAYOUT & APPEARANCE <ChevronDown size={12}/></div>{auth&&<Select id="auth-layout" label="Composition" value={bundle.site.auth.layout} options={['split','card','centered']} onChange={(v:string)=>patch('auth',{layout:v})}/>} {footer&&<Select id="footer-style" label="Footer appearance" value={bundle.site.footer.style} options={['dark','light','minimal']} onChange={(v:string)=>patch('footer',{style:v})}/>} {selection==='header'&&<Select id="header-layout" label="Header layout" value={bundle.site.header.layout} options={['classic','centered','compact','bordered']} onChange={(v:string)=>patch('header',{layout:v})}/>}<Select id="theme-heading-font" label="Heading font" value={bundle.theme.heading_font} options={['Manrope','DM Sans','Space Grotesk','IBM Plex Mono','Playfair Display','Outfit']} onChange={(v:string)=>theme({heading_font:v})}/><Select id="theme-body-font" label="Body font" value={bundle.theme.body_font} options={['DM Sans','Manrope','Space Grotesk','Outfit']} onChange={(v:string)=>theme({body_font:v})}/><div className="ed-section-label">GLOBAL COLORS</div>{[['primary','Accent'],['background','Background'],['text','Text'],['surface','Surface']].map(([key,label])=><label className="ed-color" key={key}><span>{label}</span><input data-testid={'theme-color-'+key} type="color" value={bundle.theme[key]} onChange={e=>theme({[key]:e.target.value})}/><code>{bundle.theme[key].toUpperCase()}</code></label>)}<Input id="theme-radius" label={'Corner radius · '+bundle.theme.radius+' px'} type="range" min={0} max={24} value={bundle.theme.radius} onChange={(v:string)=>theme({radius:Number(v)})}/><Toggle id="theme-motion" label="Motion" value={bundle.theme.motion} onChange={(v:boolean)=>theme({motion:v})}/></>}
 {selection==='checkout'&&tab==='content'&&<><Input id="checkout-thanks-title" label="Confirmation title" value={bundle.site.checkout.thank_you_title} onChange={(v:string)=>patch('checkout',{thank_you_title:v})}/><Input id="checkout-terms" label="Terms label" value={bundle.site.checkout.terms_label} onChange={(v:string)=>patch('checkout',{terms_label:v})}/><Toggle id="checkout-coupon" label="Coupon field" value={bundle.site.checkout.show_coupon} onChange={(v:boolean)=>patch('checkout',{show_coupon:v})}/></>}
 {!auth&&!footer&&!page&&!['header','theme','checkout'].includes(selection)&&tab==='content'&&<div className="ed-impact"><strong>System page</strong><p>Catalog and account content follows the selected customer state. Typography and colors are inherited from your theme.</p></div>}
 </div><div className="ed-inspector-footer"><i/> Changes apply to draft only</div></aside>;
};