import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {History,ArrowUpRight,RotateCcw,Check,FileClock,ShieldCheck} from 'lucide-react';
import {get,post,message} from '../../../lib/api';
import {PageTitle,Btn,Loading,Modal} from '../../../components/shared';
import {toast} from 'sonner';

export default function ReleaseHistory(){
 const [state,setState]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[pending,setPending]=useState<any>(null),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [s,r]=await Promise.all([get('/admin/builder'),get('/admin/builder/revisions')]);setState(s);setRows(r);}catch(e){setError(message(e));}};
 useEffect(()=>{load();},[]);
 const apply=async()=>{setBusy(true);try{await post('/admin/builder/'+pending.action,{version:state.version,revision_id:pending.row.id,summary:(pending.action==='rollback'?'Rollback to: ':'Restored draft: ')+pending.row.summary});toast.success(pending.action==='rollback'?'Previous presentation published. Orders and payments unchanged.':'Revision restored to draft. Live website unchanged.');setPending(null);localStorage.setItem('voltora-theme-version',String(Date.now()));await load();}catch(e){toast.error(message(e));}finally{setBusy(false);}};
 return <><PageTitle eyebrow="YOUR WEBSITE, OVER TIME" title="Release history" description="Every published version. Always a way back."><Link className="v-button" data-testid="releases-open-builder" to="/admin/website">Open website builder<ArrowUpRight size={16}/></Link></PageTitle>{error?<p data-testid="releases-error">{error}</p>:!state?<Loading/>:<div className="release-timeline" data-testid="release-history-list">{rows.map((r,i)=><article key={r.id} data-testid={'release-'+r.id} className="release-row"><div className={'release-icon '+(r.id===state.active_revision?'current':'')}><History size={20}/></div><div className="release-details"><div><h2>{r.summary}</h2>{r.id===state.active_revision&&<span className="release-live" data-testid={'active-release-'+r.id}><i/>Live now</span>}</div><p>{new Date(r.created_at).toLocaleString()} · {r.author} · {r.kind}</p><code>{r.id.slice(0,12)}</code></div><div className="release-actions"><Btn id={'restore-release-'+r.id} variant="outline" onClick={()=>setPending({row:r,action:'restore'})}><FileClock size={15}/>Restore to draft</Btn>{r.id!==state.active_revision&&<Btn id={'rollback-release-'+r.id} variant="outline" onClick={()=>setPending({row:r,action:'rollback'})}><RotateCcw size={15}/>Roll back live</Btn>}</div></article>)}</div>}<div className="release-safety"><ShieldCheck size={20}/><p>Release history contains presentation and configuration only.<br/>Completed orders, payments, inventory and customer sessions stay intact.</p></div><Modal open={!!pending} onClose={()=>!busy&&setPending(null)} title={pending?.action==='rollback'?'Publish this earlier presentation?':'Restore this version to draft?'} description={pending?.action==='rollback'?'Visitors will see this earlier design. Your current draft is preserved. Orders and payments are never restored.':'Your draft will be replaced. The published storefront remains unchanged.'}><p>{pending?.row.summary}</p><Btn id="confirm-release-action" disabled={busy} onClick={apply}>{busy?'Applying…':'Confirm'}<Check size={16}/></Btn></Modal></>;
}