import {useCallback,useEffect,useRef,useState} from 'react';
import {get,put,message,download} from '../../../lib/api';
import {useStore} from '../../../lib/store';
import {toast} from 'sonner';

export const useBuilder=()=>{
 const {user}=useStore();const recoveryKey='voltora-draft-recovery:'+user.id;
 const [data,setData]=useState<any>(null),[draft,setDraft]=useState<any>(null),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[online,setOnline]=useState(navigator.onLine);
 const [past,setPast]=useState<any[]>([]),[future,setFuture]=useState<any[]>([]);
 const latest=useRef<any>(null),saved=useRef(''),version=useRef(0),inFlight=useRef<Promise<number>|null>(null),blocked=useRef(false);
 const persist=()=>{if(latest.current)try{localStorage.setItem(recoveryKey,JSON.stringify({version:version.current,bundle:latest.current}));}catch{}};
 const load=useCallback(async(recover=true)=>{setStatus('loading');setError('');try{const d=await get('/admin/builder');let local:any=null;try{local=JSON.parse(localStorage.getItem(recoveryKey)||'null');}catch{}version.current=d.version;saved.current=JSON.stringify(d.draft);let value=d.draft;blocked.current=false;setConflict(false);if(recover&&local?.bundle&&JSON.stringify(local.bundle)!==saved.current){value=local.bundle;if(local.version!==d.version){blocked.current=true;setConflict(true);setError('A newer server draft exists. Your local changes are preserved.');}else toast.message('Your local draft has been recovered.');}latest.current=value;setDraft(value);setData(d);setPast([]);setFuture([]);setStatus(blocked.current?'conflict':JSON.stringify(value)===saved.current?'saved':'unsaved');if(!recover)localStorage.removeItem(recoveryKey);}catch(e){setError(message(e));setStatus('error');}},[recoveryKey]);
 useEffect(()=>{load();},[load]);
 const dirty=!!draft&&JSON.stringify(draft)!==saved.current;
 const save=useCallback(async():Promise<number>=>{if(inFlight.current){await inFlight.current;return save();}if(blocked.current)throw new Error('Resolve the draft conflict before saving.');if(!navigator.onLine)throw new Error('You are offline. Changes are kept on this device.');const payload=latest.current;const encoded=JSON.stringify(payload);if(encoded===saved.current)return version.current;setStatus('saving');setError('');persist();const operation=(async()=>{try{const r=await put('/admin/builder',{version:version.current,bundle:payload});version.current=r.version;saved.current=encoded;setData((d:any)=>({...d,version:r.version,updated_at:r.saved_at}));const clean=JSON.stringify(latest.current)===encoded;setStatus(clean?'saved':'unsaved');if(clean)localStorage.removeItem(recoveryKey);else persist();return r.version;}catch(e:any){persist();const code=e?.response?.status;if(code===409){blocked.current=true;setConflict(true);setStatus('conflict');}else setStatus(code===401?'expired':'error');const msg=code===401?'Your session expired. Sign in again; this draft is saved on your device.':message(e);setError(msg);throw e;}finally{inFlight.current=null;}})();inFlight.current=operation;return operation;},[recoveryKey]);
 useEffect(()=>{if(!draft||!dirty||conflict||!online)return;persist();const timer=setTimeout(()=>save().catch(()=>{}),1100);return()=>clearTimeout(timer);},[draft,conflict,online,save]);
 useEffect(()=>{const up=()=>setOnline(true),down=()=>setOnline(false);window.addEventListener('online',up);window.addEventListener('offline',down);return()=>{window.removeEventListener('online',up);window.removeEventListener('offline',down);};},[]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(JSON.stringify(latest.current)!==saved.current){persist();e.preventDefault();e.returnValue='';}};const nav=(e:MouseEvent)=>{const a=(e.target as Element).closest('a');if(a&&a.target!=='_blank'&&JSON.stringify(latest.current)!==saved.current&&!window.confirm('Your changes are saved on this device but not yet on the server. Leave the editor?')){e.preventDefault();e.stopPropagation();}};window.addEventListener('beforeunload',leave);document.addEventListener('click',nav,true);return()=>{window.removeEventListener('beforeunload',leave);document.removeEventListener('click',nav,true);};},[recoveryKey]);
 const edit=(next:any)=>{setPast(p=>[...p.slice(-49),latest.current]);setFuture([]);latest.current=next;setDraft(next);setStatus('unsaved');};
 const undo=()=>{if(!past.length)return;const value=past[past.length-1];setPast(p=>p.slice(0,-1));setFuture(f=>[latest.current,...f]);latest.current=value;setDraft(value);setStatus('unsaved');};
 const redo=()=>{if(!future.length)return;const value=future[0];setFuture(f=>f.slice(1));setPast(p=>[...p,latest.current]);latest.current=value;setDraft(value);setStatus('unsaved');};
 const exportDraft=()=>download('voltora-recovered-draft.json',JSON.stringify({version:version.current,bundle:latest.current},null,2));
 return {data,draft,status,error,conflict,online,dirty,edit,save,load,undo,redo,canUndo:!!past.length,canRedo:!!future.length,exportDraft,version};
};