import React,{useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {Panel,PanelGroup,PanelResizeHandle} from 'react-resizable-panels';
import {Monitor,Tablet,Smartphone,Undo2,Redo2,ArrowUpRight,ChevronRight,LayoutDashboard,Package,Palette,Sparkles,Settings,History,Eye,CloudCheck,CloudOff,Loader2,Save,ArrowRight,Globe,PanelsTopLeft,PanelLeft,SlidersHorizontal,Check,LockKeyhole,Download} from 'lucide-react';
import {toast} from 'sonner';
import {Logo} from '../../../components/store/Header';
import {Modal,Field,Btn} from '../../../components/shared';
import {get,post,message} from '../../../lib/api';
import {useStore} from '../../../lib/store';
import {useBuilder} from './useBuilder';
import {BuilderTree} from './BuilderTree';
import {BuilderFrame} from './BuilderFrame';
import {BuilderInspector} from './BuilderInspector';
import './builder.css';

const deviceIcons:any={desktop:Monitor,tablet:Tablet,mobile:Smartphone};
export default function VisualBuilder(){
 const b=useBuilder();const {user}=useStore();const [selection,setSelection]=useState(()=>new URLSearchParams(window.location.search).get('select')||'login'),[device,setDevice]=useState('desktop'),[customerState,setCustomerState]=useState('login'),[compare,setCompare]=useState(false),[mobilePanel,setMobilePanel]=useState('canvas'),[selectedSection,setSelectedSection]=useState<string|null>(null);
 const [publish,setPublish]=useState(false),[publishing,setPublishing]=useState(false),[summary,setSummary]=useState('Website refinements'),[newPage,setNewPage]=useState(false),[pageName,setPageName]=useState(''),[pageSlug,setPageSlug]=useState(''),[productSlug,setProductSlug]=useState('');
 const lastPath=useRef('/login');const [viewed,setViewed]=useState(['desktop']);
 useEffect(()=>{get('/products?limit=1').then(r=>setProductSlug(r.items[0]?.slug||'')).catch(()=>{});},[]);
 const canEdit=user.permissions.includes('content.update')&&user.permissions.includes('theme.update');
 const changeSelection=(id:string)=>{setSelection(id);setCompare(false);if(id==='login')setCustomerState('login');if(id==='signup')setCustomerState('signup');if(id==='forgot-password')setCustomerState('forgot');};
 const changeDevice=(id:string)=>{setDevice(id);setViewed(v=>Array.from(new Set([...v,id])));};
 let path=lastPath.current;
 if(selection.startsWith('page:'))path=selection==='page:home'?'/':'/pages/'+selection.slice(5);
 else if(selection==='product')path=productSlug?'/product/'+productSlug:'/shop';
 else if(!['footer','header','theme'].includes(selection))path='/'+selection;
 lastPath.current=path;
 const commit=async()=>{setPublishing(true);try{const version=await b.save();await post('/admin/builder/publish',{version,summary});setPublish(false);await b.load(false);localStorage.setItem('voltora-theme-version',String(Date.now()));toast.success('Your website is published.',{description:'Visitors now see the new release.'});}catch(e:any){toast.error(e.response?message(e):e.message);}finally{setPublishing(false);}};
 const addPage=(e:React.FormEvent)=>{e.preventDefault();if(b.draft.pages[pageSlug]){toast.error('That page address is already used.');return;}b.edit({...b.draft,pages:{...b.draft.pages,[pageSlug]:{title:pageName,slug:pageSlug,seo_title:pageName,seo_description:'',indexable:true,sections:[{id:'intro-'+Date.now(),type:'text',title:pageName,subtitle:'',enabled:true}]}}});changeSelection('page:'+pageSlug);setNewPage(false);setPageName('');setPageSlug('');};
 if(!b.draft)return <div className="ed-loading" data-testid="builder-loading"><Logo admin/>{b.error?<><h1>We couldn’t open your workspace.</h1><p data-testid="builder-load-error">{b.error}</p><Btn id="retry-builder-load" onClick={()=>b.load()}>Try again</Btn></>:<><Loader2 size={24} className="ed-spin"/><p>Opening your design workspace…</p></>}</div>;
 const unpublished=JSON.stringify(b.draft)!==JSON.stringify(b.data.live.bundle);
 const changes=[['Customer experience',b.draft.site.auth,b.data.live.bundle.site.auth],['Global footer',b.draft.site.footer,b.data.live.bundle.site.footer],['Global header',b.draft.site.header,b.data.live.bundle.site.header],['Checkout presentation',b.draft.site.checkout,b.data.live.bundle.site.checkout],['Theme & typography',b.draft.theme,b.data.live.bundle.theme],['Page content',b.draft.pages,b.data.live.bundle.pages]].filter(([,a,c])=>JSON.stringify(a)!==JSON.stringify(c));
 const status=!b.online?'Offline · saved on device':b.status==='saving'?'Saving draft…':b.status==='saved'?'All changes saved':b.status==='unsaved'?'Unsaved changes':b.status==='conflict'?'Draft conflict':b.status==='expired'?'Session expired':'Save needs attention';
 return <div className="ed-app" data-testid="visual-builder"><header className="ed-toolbar"><div className="ed-brand"><Logo admin/><span className="ed-toolbar-divider"/><Link data-testid="builder-workspace-home" to="/admin">Workspace</Link><ChevronRight size={13}/><span>Website builder</span><span className="ed-version-badge">BETA</span></div><div className="ed-toolbar-actions"><span className="ed-save-status" data-testid="builder-save-status">{b.status==='saving'?<Loader2 size={13} className="ed-spin"/>:!b.online?<CloudOff size={13}/>:<CloudCheck size={14}/>}<span>{status}</span></span><button title="Save draft" data-testid="builder-save-draft" className="ed-icon" disabled={!canEdit||b.status==='saving'||b.conflict} onClick={()=>b.save().then(()=>toast.success('Draft saved')).catch(e=>toast.error(e.response?message(e):e.message))}><Save size={16}/></button><Link data-testid="builder-live-store" to="/" target="_blank" className="ed-outline"><ArrowUpRight size={14}/><span>View store</span></Link><button data-testid="builder-publish" className="ed-primary" disabled={!unpublished||b.conflict||!b.online||!user.permissions.includes('content.publish')} onClick={()=>setPublish(true)}>Publish<ArrowUpRight size={15}/></button></div></header>
 <div className="ed-subtoolbar"><div><span className="ed-store-dot"/><strong>VOLTORA Store</strong><span className="ed-draft-label" data-testid="builder-release-state">{unpublished?'Unpublished changes':'Up to date'}</span></div><div className="ed-devices" aria-label="Preview device">{Object.entries(deviceIcons).map(([id,Icon]:any)=><button key={id} title={id[0].toUpperCase()+id.slice(1)+' preview'} aria-label={id+' preview'} aria-pressed={device===id} className={device===id?'active':''} data-testid={'builder-device-'+id} onClick={()=>changeDevice(id)}><Icon size={16}/></button>)}</div><div className="ed-utilities"><button className={compare?'active':''} title="Compare published release" data-testid="builder-compare-live" aria-pressed={compare} onClick={()=>setCompare(!compare)}><Eye size={15}/><span>{compare?'Viewing live':'Compare live'}</span></button><span className="ed-toolbar-divider"/><button title="Undo" data-testid="builder-undo" disabled={!b.canUndo} onClick={b.undo}><Undo2 size={15}/></button><button title="Redo" data-testid="builder-redo" disabled={!b.canRedo} onClick={b.redo}><Redo2 size={15}/></button><Link title="Release history" data-testid="builder-history" to="/admin/releases"><History size={16}/></Link></div></div>
 {b.error&&<div className="ed-error-bar" role="alert" data-testid="builder-save-error"><span>{b.error}</span><button data-testid="builder-export-recovery" onClick={b.exportDraft}><Download size={13}/>Export local draft</button>{b.status==='expired'?<a href="/admin" target="_blank" rel="noreferrer" data-testid="builder-sign-in-again">Sign in again</a>:b.conflict?<button data-testid="builder-load-latest" onClick={()=>{if(window.confirm('Replace local changes with the latest server draft? Export first to keep a copy.'))b.load(false);}}>Load latest</button>:<button data-testid="builder-retry-save" onClick={()=>b.save().catch(()=>{})}>Retry save</button>}</div>}
 <div className="ed-mobile-tabs">{[['pages','Pages',PanelLeft],['canvas','Preview',Monitor],['properties','Properties',SlidersHorizontal]].map(([id,label,Icon]:any)=><button key={id} data-testid={'builder-mobile-tab-'+id} className={mobilePanel===id?'active':''} onClick={()=>setMobilePanel(id)}><Icon size={15}/>{label}</button>)}</div>
 <div className="ed-body"><nav className="ed-rail" aria-label="Workspace shortcuts">{[['','Overview',LayoutDashboard],['products','Products',Package],['website','Website builder',PanelsTopLeft],['themes','Theme library',Palette],['ai','Mira workspace',Sparkles]].map(([id,label,Icon]:any)=><Link data-testid={'builder-nav-'+(id||'overview')} title={label} aria-label={label} className={id==='website'?'active':''} key={id} to={'/admin'+(id?'/'+id:'')}><Icon size={20}/></Link>)}<div className="ed-rail-bottom"><Link data-testid="builder-nav-settings" title="Settings" aria-label="Settings" to="/admin/settings"><Settings size={19}/></Link><span className="ed-owner-avatar" data-testid="builder-owner-initial" title={user.name}>{user.name.slice(0,1).toUpperCase()}</span></div></nav><PanelGroup direction="horizontal" className="ed-panel-group"><Panel defaultSize={17} minSize={13} maxSize={28} className={'ed-panel '+(mobilePanel==='pages'?'mobile-active':'')}><BuilderTree bundle={b.draft} selection={selection} select={changeSelection} onNewPage={()=>setNewPage(true)} selectedSection={selectedSection} setSelectedSection={setSelectedSection} edit={b.edit}/></Panel><PanelResizeHandle data-testid="builder-resize-tree" className="ed-resize"/><Panel minSize={30} className={'ed-panel '+(mobilePanel==='canvas'?'mobile-active':'')}><BuilderFrame bundle={compare?b.data.live.bundle:b.draft} selection={selection} device={device} customerState={customerState} compare={compare} path={path}/></Panel><PanelResizeHandle data-testid="builder-resize-inspector" className="ed-resize"/><Panel defaultSize={22} minSize={18} maxSize={35} className={'ed-panel '+(mobilePanel==='properties'?'mobile-active':'')}><fieldset disabled={!canEdit} className="ed-inspector-fieldset"><BuilderInspector bundle={b.draft} edit={b.edit} selection={selection} customerState={customerState} setCustomerState={setCustomerState} selectedSection={selectedSection}/></fieldset></Panel></PanelGroup></div><footer className="ed-statusbar"><span><span className="ed-blue-dot"/>Design workspace <ChevronRight size={10}/>{selection.replace('page:','')}</span><span data-testid="builder-draft-version">Draft v{b.data.version}<span className="ed-toolbar-divider"/><LockKeyhole size={10}/>External actions locked</span></footer>
 <Modal open={publish} onClose={()=>!publishing&&setPublish(false)} title="Ready for the world?" description="Publish one complete website release. Your current storefront stays unchanged until you confirm." className="ed-dialog"><div className="ed-publish-label">CHANGES IN THIS RELEASE</div><div className="ed-changes">{changes.map(([name])=><div key={name as string}><Check size={15}/><span>{name as string}</span><span>Updated</span></div>)}</div><div className="ed-review-devices">{Object.entries(deviceIcons).map(([id,Icon]:any)=><button data-testid={'publish-review-'+id} key={id} onClick={()=>{changeDevice(id);setPublish(false);}}><Icon size={20}/><span>{id}</span>{viewed.includes(id)?<Check size={13}/>:<ArrowUpRight size={13}/>}</button>)}</div><Field id="publish-summary" label="Release note" value={summary} minLength={3} maxLength={240} onChange={(e:any)=>setSummary(e.target.value)}/><div className="ed-publish-safe"><LockKeyhole size={16}/><p>Presentation only. Orders, payments, customer accounts and saved carts are not changed.</p></div><button className="ed-primary wide" data-testid="confirm-publish" disabled={publishing||summary.trim().length<3} onClick={commit}>{publishing?'Publishing…':'Publish website'}<ArrowRight size={16}/></button></Modal>
 <Modal open={newPage} onClose={()=>setNewPage(false)} title="A new page, a new possibility." description="Create a custom page in your private draft." className="ed-dialog"><form onSubmit={addPage}><Field id="new-page-name" label="Page name" required maxLength={80} value={pageName} onChange={(e:any)=>{setPageName(e.target.value);setPageSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));}}/><Field id="new-page-slug" label="Page address" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={80} value={pageSlug} onChange={(e:any)=>setPageSlug(e.target.value)}/><button className="ed-primary wide" data-testid="new-page-create" type="submit">Create draft page<ArrowRight size={16}/></button></form></Modal>
 </div>;
}