import React,{useState,useEffect} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Sparkles,Send,Headset} from 'lucide-react';
import {useStore} from '../lib/store';
import {get,post,API_ROOT,message} from '../lib/api';
import {Btn,Field,Empty} from '../components/shared';
import {toast} from 'sonner';

export const Assistant=()=>{
 const {user,config}=useStore();const navigate=useNavigate();const [name,setName]=useState(user?.name||''),[email,setEmail]=useState(user?.email||''),[prompt,setPrompt]=useState(''),[active,setActive]=useState<any>(null),[conversation,setConversation]=useState<any>(null),[output,setOutput]=useState(''),[busy,setBusy]=useState(false),[tools,setTools]=useState<any[]>([]);
 const load=(c=active)=>{if(c)get(`/support/conversations/${c.id}?access=${c.access}`).then(setConversation);};
 const send=async(e:any)=>{e.preventDefault();setBusy(true);setOutput('');try{let c=active;const message=prompt;if(!c){c=await post('/support/conversations',{name,email,subject:prompt.slice(0,100),message:prompt,order_id:'',order_access:'',use_ai:true});setActive(c);const saved=JSON.parse(localStorage.getItem('voltora-support')||'[]');localStorage.setItem('voltora-support',JSON.stringify([{...c,subject:prompt.slice(0,100),status:'open'},...saved]));}setPrompt('');const response=await fetch(`${API_ROOT}/assistant/chat`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:c.id,message,access:c.access||''})});if(!response.ok)throw new Error((await response.json()).detail);const reader=response.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){if(!chunk.startsWith('data:'))continue;const ev=JSON.parse(chunk.slice(5));if(ev.tools)setTools(ev.tools);if(ev.text)setOutput(ev.text);if(ev.error)toast.error(ev.error);}}setOutput('');setTools([]);load(c);}catch(e:any){toast.error(e.message||message(e));}finally{setBusy(false);}};
 if(!config.settings.features.ai_chat)return <Empty icon={Headset} title="Our human team is here for you." description="The AI assistant is not currently connected." link="/support" label="Contact support"/>;
 return <div className="container support-page"><span className="eyebrow">VOLTORA AI ASSISTANT</span><h1>Let’s find your fit.</h1><p className="support-intro">An AI assistant for product discovery. Verify important details with our human team.</p><div className="assistant-layout"><div className="support-main"><div className="message-list">{conversation?.messages.map((m:any)=><div key={m.id} className={'chat-message '+m.sender} data-testid={`assistant-message-${m.id}`}><span>{m.name}</span><p>{m.text}</p></div>)}{output&&<div className="chat-message ai" data-testid="assistant-stream"><span>VOLTORA AI assistant</span>{tools.length>0&&<small className="block" style={{opacity:.7}}>{tools.map((t:any,i:number)=><span key={i} className="mono" style={{fontSize:10,marginRight:8}}>· {t.tool}</span>)}</small>}<p>{output}</p></div>}</div><form onSubmit={send}>{!active&&<div className="field-grid"><Field id="assistant-name" label="Your name" required value={name} onChange={(e:any)=>setName(e.target.value)}/><Field id="assistant-email" label="Email for support continuity" type="email" required value={email} onChange={(e:any)=>setEmail(e.target.value)}/></div>}<div className="reply-form"><input data-testid="assistant-question" required minLength={3} placeholder="What are you looking for?" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button data-testid="assistant-send" title="Send to AI assistant" disabled={busy} type="submit"><Send size={20}/></button></div></form><Btn id="assistant-human-handoff" variant="outline" disabled={busy} onClick={async()=>{if(active){await post(`/support/conversations/${active.id}/handoff?access=${active.access}`);navigate(`/support?conversation=${active.id}&access=${active.access}`);}else navigate('/support');}}><Headset size={17}/>Talk to a human instead</Btn></div></div></div>;
};