import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Check,ShieldCheck,Eye,EyeOff} from 'lucide-react';
import {useStore} from '../lib/store';
import {post,message} from '../lib/api';
import {Field,Btn} from '../components/shared';
import './customer-auth.css';

export const CustomerAuth=({initial='login'}:{initial?:string;admin?:boolean})=>{
 const {config,inPreview,login}=useStore();const auth=config?.site?.auth||{};
 const [mode,setMode]=useState(initial),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false);
 useEffect(()=>{if(inPreview&&config.customerPreviewState){setMode(config.customerPreviewState);setSuccess(false);setError('');}},[config.customerPreviewState,inPreview]);
 const current=mode;
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(inPreview){setSuccess(true);return;}setBusy(true);setError('');try{if(current==='forgot'){throw new Error('Recovery delivery is not connected. Contact the store owner for identity-verified recovery.');}const data=await post('/auth/'+(current==='signup'?'register':'login'),{email,password,...(current==='signup'?{name}:{})});login(data);setSuccess(true);}catch(e:any){setError(e.response?message(e):e.message);}finally{setBusy(false);}};
 const title=current==='signup'?'Make yourself at home.':current==='forgot'?'A fresh start.':auth.form_title||'Welcome back.';
 return <section className={'customer-auth ca-'+(auth.layout||'split')} data-testid="customer-auth-preview"><div className="ca-art"><img src={auth.side_image||'/assets/voltora-headphones.jpg'} alt="VOLTORA headphones collection"/><div className="ca-art-copy"><span>THOUGHTFULLY CONNECTED.</span><h1 data-testid="customer-side-heading">{auth.side_heading||'Made for the way you live.'}</h1><p data-testid="customer-side-text">{auth.side_text||'Good things feel even better together.'}</p></div><span className="ca-art-number">VOLTORA / EVERYDAY, UPGRADED</span></div><div className="ca-form-wrap"><span className="ca-eyebrow">YOUR VOLTORA ACCOUNT</span><h2 data-testid="customer-form-title">{title}</h2><p>{current==='signup'?'A few details. A world of possibilities.':current==='forgot'?'Enter the email linked to your account.':'Good to see you again. Make yourself at home.'}</p>
 {(success||current==='success')?<div className="ca-success" role="status" data-testid="customer-auth-success"><Check size={28}/><h3>{inPreview?'You’re all set.':'You’re signed in.'}</h3><p>{inPreview?'Customer success state':'Your account is ready.'}</p>{!inPreview&&<Link data-testid="customer-open-account" to="/account">Open your account <ArrowRight size={16}/></Link>}</div>:<form onSubmit={submit}>{current==='signup'&&<Field id="customer-name" label="Your name" required minLength={2} value={name} onChange={(e:any)=>setName(e.target.value)}/>}<Field id="customer-email" label="Email address" type="email" placeholder="you@example.com" autoComplete={inPreview?'off':'email'} required value={email} onChange={(e:any)=>setEmail(e.target.value)}/>{current!=='forgot'&&<div className="ca-password"><Field id="customer-password" label="Password" type={show?'text':'password'} autoComplete={inPreview?'off':current==='signup'?'new-password':'current-password'} required minLength={current==='signup'?10:1} value={password} onChange={(e:any)=>setPassword(e.target.value)}/><button type="button" aria-label="Toggle password visibility" data-testid="customer-password-visibility" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>}{current==='error'&&<p className="ca-error" role="alert" data-testid="customer-preview-error">That email and password don’t match. Please try again.</p>}{error&&<p role="alert" data-testid="customer-auth-error" className="ca-error">{error}</p>}{current==='login'&&<button type="button" className="ca-forgot" data-testid="customer-forgot-password" onClick={()=>setMode('forgot')}>Forgot password?</button>}<Btn type="submit" id="customer-auth-submit" disabled={busy||current==='forgot'&&!inPreview}>{busy?'Please wait…':current==='signup'?'Create account':current==='forgot'?'Send reset link':auth.button_label||'Sign in'}<ArrowRight size={17}/></Btn>{current==='forgot'&&!inPreview&&<p className="ca-error" data-testid="recovery-unavailable">Recovery delivery is not connected. Contact the store owner.</p>}</form>}
 <div className="ca-switch">{current==='login'?'New to VOLTORA?':'Already have an account?'} <button data-testid="customer-auth-switch" onClick={()=>{setMode(current==='login'?'signup':'login');setSuccess(false);setError('');}}>{current==='login'?'Create an account':'Sign in'}</button></div><div className="ca-note"><ShieldCheck size={15}/><span data-testid="customer-card-note">{auth.card_note||'Your details, treated with care.'}</span></div></div></section>;
};