import React,{useEffect,useState} from 'react';
import {useSearchParams,Link} from 'react-router-dom';
import {Headset,ArrowRight,Send,Plus,MessageCircle,Clock,ChevronRight} from 'lucide-react';
import {useStore} from '../lib/store';
import {get,post,message} from '../lib/api';
import {Btn,Field,Loading,Status} from '../components/shared';
import {toast} from 'sonner';

export const Support=()=>{
 const {user,config}=useStore();const [params]=useSearchParams();const [list,setList]=useState<any[]>([]),[active,setActive]=useState<any>(null),[conversation,setConversation]=useState<any>(null),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({name:user?.name||'',email:user?.email||'',subject:params.get('order')?'Help with my order':'',message:''});
 useEffect(()=>{if(params.get('conversation'))setActive({id:params.get('conversation'),access:params.get('access')||''});},[params]);
 useEffect(()=>{if(user)get('/support/conversations').then(setList);else{try{setList(JSON.parse(localStorage.getItem('voltora-support')||'[]'));}catch{}}},[user]);
 const load=()=>{if(active)get(`/support/conversations/${active.id}?access=${active.access||''}`).then(setConversation).catch(e=>toast.error(message(e)));};
 useEffect(()=>{load();const timer=active?setInterval(load,12000):null;return()=>{if(timer)clearInterval(timer);};},[active]);
 const create=async(e:any)=>{e.preventDefault();setBusy(true);try{const r=await post('/support/conversations',{...form,order_id:params.get('order')||'',order_access:params.get('access')||''});const item={...r,subject:form.subject,status:'open'};setList([item,...list]);if(!user)localStorage.setItem('voltora-support',JSON.stringify([item,...list]));setActive(item);toast.success('Your message is with our team');}catch(e){toast.error(message(e));}finally{setBusy(false);}};
 const send=async(e:any)=>{e.preventDefault();if(!reply.trim())return;try{await post(`/support/conversations/${active.id}/messages?access=${active.access||''}`,{text:reply,internal:false});setReply('');load();}catch(e){toast.error(message(e));}};
 if(!config.settings.features.support)return <div className="container support-page"><h1>Support messaging is unavailable.</h1><p>Visit the contact page for available contact details.</p><Link className="v-button" to="/pages/contact" data-testid="support-contact">Contact details</Link></div>;
 return <div className="container support-page"><span className="eyebrow">REAL PEOPLE. REAL SUPPORT.</span><h1 data-testid="support-title">A little help goes a long way.</h1><p className="support-intro">Product questions, order updates, or just a little advice. We’re here for you.</p><div className="support-layout"><aside><div className="support-availability"><Headset size={25}/><div><strong>VOLTORA care</strong><span><i/>Offline · Leave us a message</span></div></div><Btn id="new-conversation" variant="outline" onClick={()=>{setActive(null);setConversation(null);}}><Plus size={16}/>New conversation</Btn><div className="conversation-list">{list.map(c=><button key={c.id} data-testid={`conversation-${c.id}`} className={active?.id===c.id?'active':''} onClick={()=>setActive(c)}><MessageCircle size={17}/><span>{c.subject}<small>{c.status}</small></span><ChevronRight size={15}/></button>)}</div></aside><section className="support-main">{!active?<><div className="support-form-title"><MessageCircle size={25}/><div><h2>What’s on your mind?</h2><p>Leave a message. Our team will reply in this conversation.</p></div></div><form onSubmit={create}><div className="field-grid"><Field id="support-name" label="Your name" required value={form.name} onChange={(e:any)=>setForm({...form,name:e.target.value})}/><Field id="support-email" label="Email address" type="email" required value={form.email} onChange={(e:any)=>setForm({...form,email:e.target.value})}/></div><Field id="support-subject" label="Subject" minLength={3} required value={form.subject} onChange={(e:any)=>setForm({...form,subject:e.target.value})}/><Field id="support-message" label="How can we help?" as="textarea" rows={5} required value={form.message} onChange={(e:any)=>setForm({...form,message:e.target.value})}/><Btn id="support-submit" className="primary" disabled={busy} type="submit">Send message<ArrowRight size={17}/></Btn></form></>:!conversation?<Loading/>:<><div className="conversation-header"><h2 data-testid="conversation-subject">{conversation.subject}</h2><Status id="conversation-status" value={conversation.status}/></div><div className="message-list">{conversation.messages.map((m:any)=><div key={m.id} className={'chat-message '+m.sender} data-testid={`message-${m.id}`}><span>{m.name} · {new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><p>{m.text}</p></div>)}</div><form className="reply-form" onSubmit={send}><input data-testid="support-reply" aria-label="Reply" required placeholder="Your message..." value={reply} onChange={e=>setReply(e.target.value)}/><button type="submit" data-testid="support-send-reply" aria-label="Send reply"><Send size={20}/></button></form></>}</section></div></div>;
};