import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,ShoppingBag,Package,Users,Wallet,Plus,Check,Palette,Plug,Globe,Sparkles,Mail,ChevronRight,CalendarDays,ShieldCheck,Activity} from 'lucide-react';
import {get,message} from '../../lib/api';
import {useStore} from '../../lib/store';
import {adminHref} from '../../lib/adminPath';
import {Loading,Status} from '../../components/shared';
export const Overview=()=>{const [data,setData]=useState<any>(null),[error,setError]=useState('');const {money,config,user}=useStore();useEffect(()=>{get('/admin/overview').then(setData).catch(e=>setError(message(e)));},[]);if(error)return <div className="admin-panel"><h2>We couldn’t load your overview.</h2><p>{error}</p></div>;if(!data)return <Loading/>;const metrics=[['Total revenue',money(data.revenue,true),Wallet,'Paid orders only'],['Orders',data.orders,ShoppingBag,`${data.unpaid} awaiting payment`],['Active products',data.products,Package,`${data.low_stock.length} low-stock variants`],['Customers',data.customers,Users,'Registered accounts']];return <>
<div className="overview-heading"><div><span className="eyebrow">YOUR STORE AT A GLANCE</span><h1 data-testid="admin-page-title">A little clarity. A lot of possibility.</h1><p>Welcome back. Here’s what’s happening with your store.</p></div><Link className="v-button outline" data-testid="overview-visit-store" to="/">View store<ArrowUpRight size={16}/></Link></div>
<div className="workspace-hero"><div className="workspace-hero-copy"><span className="hero-kicker"><i/> YOUR NEXT CHAPTER STARTS HERE</span><h2>Good ideas deserve<br/>a great storefront.</h2><p>Your products. Your point of view.<br/>Make every detail unmistakably yours.</p><Link data-testid="overview-build-store" to={adminHref('website')} className="v-button primary">Make it yours <ArrowUpRight size={17}/></Link><Link data-testid="overview-browse-themes" to={adminHref('themes')} className="hero-secondary">Explore themes<ArrowRight size={15}/></Link></div><img src="/assets/voltora-headphones.jpg" alt="Premium headphones from the demonstration collection"/><span className="workspace-hero-index">VOLTORA / DESIGNED FOR POSSIBILITY</span></div>
<div className="overview-context"><span><i/> Isolated demonstration · real workspace, sample catalog</span><span><CalendarDays size={14}/>All time</span></div>
<div className="admin-metrics overview-metrics">{metrics.map(([label,value,Icon,note]:any,i)=><div className="metric" key={label}><div className="metric-label"><span>{label}</span><Icon size={17}/></div><strong data-testid={'metric-'+['revenue','orders','products','customers'][i]}>{value}</strong><small>{note}</small></div>)}</div>
<div className="overview-main-grid"><section className="admin-panel recent-orders-panel"><div className="panel-heading"><div><h2>Recent orders</h2><p>The latest from your checkout.</p></div><Link className="text-link" data-testid="overview-all-orders" to={adminHref('orders')}>View all<ArrowUpRight size={15}/></Link></div>{data.recent_orders.length?<div className="table-scroll"><table className="admin-table"><thead><tr><th>Order</th><th>Payment</th><th>Status</th><th>Amount</th></tr></thead><tbody>{data.recent_orders.slice(0,5).map((o:any)=><tr key={o.id}><td><Link data-testid={'overview-order-'+o.id} to={adminHref('orders')}>{o.number}</Link></td><td><Status value={o.payment_status}/></td><td><Status value={o.status}/></td><td>{money(o.total,true)}</td></tr>)}</tbody></table></div>:<div className="order-empty"><span className="order-empty-icon"><ShoppingBag size={27} strokeWidth={1.3}/></span><h3>Your first order starts a story.</h3><p>Orders will appear here as customers check out.<br/>Explore the storefront to place an isolated test order.</p><Link className="text-link" data-testid="overview-test-order" to="/shop">Explore your store<ArrowRight size={15}/></Link></div>}</section>
<section className="admin-panel launch-panel"><div className="panel-heading"><div><span className="eyebrow">A STRONG FOUNDATION</span><h2>Make yourself at home</h2></div><span className="setup-counter">1 / 4</span></div>{[[Package,'Meet your catalog',`${data.products} products ready to explore`,'products',true],[Palette,'Find your visual voice','Try a theme. Make it your own.','themes',false],[Mail,'Give your brand an inbox','Plan domain addresses and compose drafts','mail',false],[Plug,'Connect your essentials','Payment, email and shipping providers','connections',false]].map(([Icon,title,text,path,done]:any)=><Link className="setup-step" data-testid={'setup-'+path} to={adminHref(path)} key={path}><span className={'setup-step-icon '+(done?'done':'')}>{done?<Check size={16}/>:<Icon size={17}/>}</span><span><b>{title}</b><small>{text}</small></span><ChevronRight size={16}/></Link>)}<div className="setup-note"><ShieldCheck size={16}/><span>Live operation requires verified providers.<br/>No charges or messages leave this demo.</span></div></section></div>
<div className="overview-bottom-grid"><Link className="workspace-shortcut" to={adminHref('ai')} data-testid="overview-ai"><span className="shortcut-icon"><Sparkles size={23}/></span><div><span className="eyebrow">A LITTLE EXTRA PERSPECTIVE</span><h3>Meet your creative co-pilot.</h3><p>Your AI account. Your direction. Review every change.</p></div><ArrowUpRight size={22}/></Link><section className="admin-panel activity-panel"><div className="panel-heading"><h2>Latest activity</h2><Activity size={17}/></div>{data.activity.length?data.activity.slice(0,2).map((a:any)=><div className="activity-line" key={a.id}><i/><span><b>{a.action.replaceAll('.',' · ').replaceAll('_',' ')}</b><small>{a.actor} · {new Date(a.created_at).toLocaleDateString()}</small></span></div>):<p className="activity-empty">Nothing to catch up on. Your workspace actions will appear here.</p>}</section></div></>;};

export default Overview;