import React,{useState,useEffect,useRef} from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import {ArrowUpRight,ArrowLeft,Eye,Check,Search,Monitor,Tablet,Smartphone,Sun,Moon,Palette,Settings2,ChevronRight,Grid2X2,X} from 'lucide-react';
import {get,put,message} from '../../lib/api';
import {useStore} from '../../lib/store';
import {PageTitle,Btn,Loading,Field} from '../../components/shared';
import {ThemeStudio} from './DesignStudio';
import {toast} from 'sonner';
import {Navigate} from 'react-router-dom';
const frames=['Homepage','Collection','Product','Cart','Checkout','Account','Support','Content','404','Maintenance'];
const paths=['/','/shop','/product/auralis-studio-h1','/cart','/checkout','/account','/support','/pages/about','/not-a-page','/'];
const themePreviewUrl=(id:string,path='/',appearance='light')=>path+'?theme_preview='+encodeURIComponent(id)+'&appearance='+appearance;
export const ThemeGallery=()=>{const {config,user}=useStore();const [themes,setThemes]=useState<any[]>([]),[q,setQ]=useState(''),[category,setCategory]=useState('all'),[studio,setStudio]=useState(false),[selected,setSelected]=useState<any>(null),[device,setDevice]=useState('desktop'),[appearance,setAppearance]=useState('light'),[screen,setScreen]=useState(0),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[zoom,setZoom]=useState(1);const area=useRef<HTMLDivElement>(null);
useEffect(()=>{get('/admin/themes').then(setThemes).catch(e=>setError(message(e)));},[]);useEffect(()=>{const node=area.current;if(!node)return;const resize=()=>setZoom(Math.min(1,(node.clientWidth-24)/(device==='mobile'?390:device==='tablet'?768:1440)));resize();const observer=new ResizeObserver(resize);observer.observe(node);return()=>observer.disconnect();},[selected,device]);
const apply=async(t:any)=>{setBusy(true);try{const doc=await get('/admin/documents/theme');await put('/admin/documents/theme',{value:t,version:doc.version});toast.success('Theme saved as a draft. Your published store is unchanged.');setSelected(null);setStudio(true);}catch(e){toast.error(message(e));}finally{setBusy(false);}};
if(studio)return <Navigate to="/admin/website?select=theme" replace/>;
if(!config?.theme)return <Loading text="Loading the published theme…"/>;
const categories=['all',...Array.from(new Set(themes.map(t=>t.industry||'general')))];const filtered=themes.filter(t=>(category==='all'||t.industry===category)&&(t.name+' '+t.description).toLowerCase().includes(q.toLowerCase()));const shown=filtered.slice((page-1)*6,page*6);
return <><PageTitle eyebrow="A DIFFERENT POINT OF VIEW" title="A store that feels like you." description="Considered themes. Real storefronts. Your next starting point."><Btn id="open-theme-studio" variant="outline" onClick={()=>setStudio(true)}><Settings2 size={16}/>Customize current theme</Btn></PageTitle>
<div className="theme-live-strip"><div className="theme-live-icon"><Palette size={23}/></div><div><span className="eyebrow">YOUR PUBLISHED THEME</span><h2>{config.theme.name}</h2><p>Your content and catalog stay yours when you change the design.</p></div><span className="status status-published">Published</span><Btn id="customize-live-theme" className="primary" onClick={()=>setStudio(true)}>Make it yours<ArrowUpRight size={15}/></Btn></div>
<div className="theme-library-toolbar"><div className="theme-category-tabs">{categories.map(c=><button className={category===c?'active':''} key={c} data-testid={'theme-category-'+c} onClick={()=>{setCategory(c);setPage(1);}}>{c==='all'?'All themes':c.replaceAll('_',' ')}</button>)}</div><div className="table-search"><Search size={16}/><input data-testid="theme-gallery-search" aria-label="Search themes" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Find your next look…"/></div></div>
<div className="theme-results-note"><span>{filtered.length} carefully considered starting points</span><span><Eye size={13}/>Rendered previews · not screenshots</span></div>
{error?<p className="form-error">{error}</p>:!themes.length?<Loading/>:<div className="theme-real-grid">{shown.map((t,i)=><article className="real-theme-card" key={t.id} data-testid={'real-theme-'+t.id}><div className="real-theme-frame"><div className="mini-browser"><i/><i/><i/><span>{t.name.toLowerCase().replaceAll(' ','')}.voltora</span><Monitor size={11}/></div><div className="real-theme-viewport"><iframe tabIndex={-1} name="voltora-preview" sandbox="allow-scripts allow-same-origin" title={t.name+' rendered homepage'} src={themePreviewUrl(t.id)} loading="lazy"/><button className="theme-preview-overlay" data-testid={'theme-preview-'+t.id} onClick={()=>{setSelected(t);setScreen(0);}} aria-label={'Open interactive '+t.name+' preview'}><span><Eye size={16}/>Explore this theme<ArrowUpRight size={15}/></span></button></div></div><div className="real-theme-info"><div><span className="theme-number">{String((page-1)*6+i+1).padStart(2,'0')}</span><h2>{t.name}</h2>{config.theme.id===t.id&&<span className="status status-published">Current</span>}</div><p>{t.description}</p><footer><span className="theme-industry-label">{t.industry||'General'}<i/>Light & dark</span><button data-testid={'theme-details-'+t.id} onClick={()=>{setSelected(t);setScreen(0);}} className="text-link">Preview<ArrowUpRight size={15}/></button></footer></div></article>)}</div>}
{!filtered.length&&themes.length>0&&<div className="empty"><Search size={27}/><h2>No themes found.</h2><p>Try another category or search.</p></div>}
{filtered.length>6&&<div className="pagination"><Btn id="theme-page-prev" variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Btn><span>{page} / {Math.ceil(filtered.length/6)}</span><Btn id="theme-page-next" variant="outline" disabled={page*6>=filtered.length} onClick={()=>setPage(page+1)}>Next</Btn></div>}
{selected&&<DialogPrimitive.Root open onOpenChange={open=>{if(!open)setSelected(null);}}><DialogPrimitive.Portal><DialogPrimitive.Content className="full-theme-preview" aria-label="Interactive theme preview" aria-describedby="theme-preview-desc"><header><button data-testid="close-theme-preview" className="icon-btn" aria-label="Close preview" onClick={()=>setSelected(null)}><X size={19}/></button><div><DialogPrimitive.Title asChild><b>{selected.name}</b></DialogPrimitive.Title><DialogPrimitive.Description id="theme-preview-desc" asChild><span>Isolated interactive preview</span></DialogPrimitive.Description></div><div className="theme-preview-controls">{[['desktop',Monitor],['tablet',Tablet],['mobile',Smartphone]].map(([d,Icon]:any)=><button key={d} data-testid={'gallery-device-'+d} className={'icon-btn '+(device===d?'active':'')} aria-label={d+' preview'} onClick={()=>setDevice(d)}><Icon size={17}/></button>)}<button className="icon-btn" data-testid="gallery-appearance-toggle" aria-label="Toggle preview light and dark" onClick={()=>setAppearance(appearance==='light'?'dark':'light')}>{appearance==='light'?<Moon size={17}/>:<Sun size={17}/>}</button></div><Btn id="theme-use-draft" className="primary" disabled={busy||!user.permissions.includes('theme.update')} onClick={()=>apply(selected)}>Use as draft<ArrowUpRight size={15}/></Btn></header><div className="theme-page-switcher">{frames.map((p,i)=><button data-testid={'preview-page-'+p.toLowerCase()} key={p} className={screen===i?'active':''} onClick={()=>setScreen(i)}>{p}</button>)}</div><div className="full-preview-area" ref={area}><div className="scaled-theme-frame" style={{width:(device==='mobile'?390:device==='tablet'?768:1440)*zoom,height:`calc((100vh - 150px))`}}><iframe name="voltora-preview" title="Navigable isolated theme preview" data-testid="interactive-theme-preview" sandbox="allow-scripts allow-same-origin" src={themePreviewUrl(selected.id,paths[screen],appearance)+(screen===9?'&maintenance_preview=1':'')} style={{width:device==='mobile'?390:device==='tablet'?768:1440,height:(window.innerHeight-150)/zoom,transform:`scale(${zoom})`,transformOrigin:'top left'}}/></div></div><div className="theme-preview-safety"><ShieldIcon/>Preview changes never publish or create orders. Use as draft to customize, then publish explicitly.</div></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>}
</>;};
const ShieldIcon=()=> <Eye size={13}/>;
